export const CLOSE_MODAL = "CLOSE_MODAL";
export const OPEN_MODAL = "OPEN_MODAL";
export const OPEN_FORM_EDIT_PROJECT = "OPEN_FORM_EDIT_PROJECT";
export const SET_SUBMIT_EDIT_PROJECT = "SET_SUBMIT_EDIT_PROJECT";
export const SET_SUBMIT_CREATE_TASK = "SET_SUBMIT_CREATE_TASK";
export const OPEN_FORM_CREATE_TASK = "OPEN_FORM_CREATE_TASK";
export const SET_SUBMIT_EDIT_USER = "SET_SUBMIT_EDIT_USER";
export const OPEN_FORM_EDIT_USER = "OPEN_FORM_EDIT_USER";