export const USER_SIGNIN_API = "USER_SIGNIN_API";
export const USER_LOGIN_TYPE = "USER_LOGIN_TYPE";
export const GET_ALL_PROJECT_CATEGORY = "GET_ALL_PROJECT_CATEGORY";
export const GET_ALL_PROJECT_CATEGORY_SAGA = "GET_ALL_PROJECT_CATEGORY_SAGA";
